name: jenkins
version: 2.8
summary: Jenkins automation server
description: Continuous integration and delivery server with a vast ecosystem of plugins
confinement: strict
apps:
    jenkins:
        command: java -DJENKINS_HOME="$SNAP_DATA" -Djava.awt.headless=true -jar $SNAP/war/jenkins.war
        plugs: [network, network-bind]
        daemon: simple
    config:
        command: jenkins-config
parts:
    jenkins:
        plugin: jenkins
        source: https://github.com/jenkinsci/jenkins
        source-tag: jenkins-2.8
        source-type: git
        stage-packages:
            # Jenkins wants fonts.
            - fonts-dejavu-core
        snap:
            - war/jenkins.war
            - usr/lib/jvm/default-java/bin
            - usr/lib/jvm/default-java/lib
            - usr/lib/jvm/default-java/jre/bin
            - usr/lib/jvm/default-java/jre/lib
            - etc/java-*
            # Jenkins wants fonts.
            - etc/fonts/fonts.conf
            - usr/share/fonts
            - usr/lib/*/libfontconfig*
    git:
        # Git support.
        plugin: nil
        stage-packages:
            - git
        snap:
            - usr/bin/git*
            - usr/lib/git*
            - usr/lib/*/libasn1.so*
            - usr/lib/*/libcurl-gnutls.so*
            - usr/lib/*/libffi.so*
            - usr/lib/*/libgmp.so*
            - usr/lib/*/libgnutls.so*
            - usr/lib/*/libgssapi.so*
            - usr/lib/*/libgssapi_krb5.so*
            - usr/lib/*/libhcrypto.so*
            - usr/lib/*/libheimbase.so*
            - usr/lib/*/libheimntlm.so*
            - usr/lib/*/libhogweed.so*
            - usr/lib/*/libhx509.so*
            - usr/lib/*/libidn.so*
            - usr/lib/*/libk5crypto.so*
            - usr/lib/*/libkrb5.so*
            - usr/lib/*/libkrb5support.so*
            - usr/lib/*/liblber-2.4.so*
            - usr/lib/*/libldap_r-2.4.so*
            - usr/lib/*/libnettle.so*
            - usr/lib/*/libp11-kit.so*
            - usr/lib/*/libroken.so*
            - usr/lib/*/librtmp.so*
            - usr/lib/*/libsasl2.so*
            - usr/lib/*/libsqlite3.so*
            - usr/lib/*/libtasn1.so*
            - usr/lib/*/libwind.so*
    config:
        plugin: copy
        files:
            jenkins-config: bin/jenkins-config

# vim: set ai et sts=4 tabstop=4 sw=4:
